version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-junia
    ports:
      - "8080:80"   # Ton site sera dispo sur http://localhost:8080
    volumes:
      - /var/www/html/Junia-2025:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - junia-net

  php:
    image: php:8.2-fpm
    container_name: php-junia
    volumes:
      - /var/www/html/Junia-2025:/var/www/html
    networks:
      - junia-net

  mysql:
    image: mysql:latest
    container_name: mysql-junia
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123
      MYSQL_DATABASE: junia_db
      MYSQL_USER: junia_user
      MYSQL_PASSWORD: JuniaPass123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # MySQL Docker dispo sur 3307
    networks:
      - junia-net

networks:
  junia-net:

volumes:
  mysql_data:
