name: CI Pipeline

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run PHP lint
        run: |
          errors=0
          while IFS= read -r -d '' file; do
            echo "Linting $file"
            if ! php -l "$file"; then
              errors=$((errors+1))
            fi
          done < <(find . -type f -name "*.php" ! -path "./vendor/*" -print0)

          if [ $errors -gt 0 ]; then
            echo "$errors file(s) have syntax errors."
            exit 1
          else
            echo "All PHP files are valid!"
          fi

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/Junia-2025:latest .

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/junia-2025:latest
